# Generated by Django 5.2 on 2025-05-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='consumed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
